# Generated by Django 4.1.1 on 2022-10-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preface', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('extLink', models.URLField()),
                ('description', models.TextField()),
                ('image', models.FilePathField(path='/images')),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
